### ISSUE TITLE
IE11 clear button breaks value imprint

### ISSUE THREAD

**Issue by brianblakely** [brianblakely/nodep-date-input-polyfill#18]
When an input's native clear button is clicked, that field's value can no longer be set by JavaScript.  That functionality must be disabled.

Snippet to do this (nest in SCSS):

```css
::-ms-clear {
  display: none;
}
```
