### ISSUE TITLE
How can i overidde the zindex of the popup date selector?

### ISSUE THREAD

**Issue by japrogramer** [brianblakely/nodep-date-input-polyfill#62]
I would like to change the z-index of the popup date picker ..
when i do
<input type='date' style="z-index: 2000 !important" />
the zindex for the picker remains the same

**Comment by brianblakely** [comment]
You must change the z-index for `date-input-polyfill`:

```css
date-input-polyfill {
  z-index: NEW_VALUE_HERE;
}
```

If this does not work, there is an unrelated application problem.
